### ISSUE TITLE
[Proposal] Composer Installer

### ISSUE THREAD

**Issue by alexrussell** [rtablada/package-installer#10]
Maybe I'm crazy but this feels like reinventing the wheel somewhat (which Laravel is generally against). The automatic updating of app config, etc. are great, and that's useful functionality that's not done elsewhere, but Laravel uses composer for package management - why not leverage that better and make this not a strict Laravel plugin but a [composer installer](http://getcomposer.org/doc/articles/custom-installers.md) (this is what composer installers were made for)? (You get a lot of other stuff for free: no need to use provides.json; just hook into composer.json extras; it'll know which packages to hook into and which not to; package dependency resolution is sorted by virtue of normal composer stuff.)

I actually started work on exactly this recently before finding this package, which has kinda brought me to a halt as there's no point in me redoing this work, but at the same time this implementation is good but naïve to composer installers.

With a composer installer, you can hook into install, update and uninstall events and execute whatever code you want.

**Comment by rtablada** [comment]
Not sure a about the composer installer possibility.

Right now dev on the installer is a bit on hold until I can sit down a bit more with some more of the core team.

I'll see if I can't grab the ear of some of the composer guys.

**Comment by alexrussell** [comment]
I really think that doing this as a composer installer is the way forward. But I think that really this functionality should be integrated into Laravel's core packages eventually. That way no-one will **ever** have to "add the service provider to app/config/app.php" - this one's in by default, and then this package automatically does that for people from then on.

I understand that you may wish to do it as a Laravel installer for the artisan stuff like search, but this stuff already comes for free with composer. Plus by all means make it a laravel package and composer installer - anything that can't be done using composer can still have an artisan command, but otherwise we should leverage the stuff we're given, no?

What's the licence on this project, by the way? Sorry if there's one and I missed it.

**Comment by rtablada** [comment]
License is MIT as listed in the composer.json file.

Taylor and I have been talking about including this into core for 4.1 (there's some question about the best abstraction of things).

Like I said, the core team and I have to talk things over on best practices, but the Composer installer does not quite seem like what is desired for the L4 package installer.
1. From what I'm reading composer installers only run on `composer install` thus when someone has run `composer create-project laravel/laravel` and adds a dependency to their project it won't run.
2. In terms of LPM search vs composer search, the search in package manager is not the same functionality as the standard composer search: it includes an `LPM` tag
3. Just because composer gives us a tool doesn't mean we shouldn't create abstractions for it. This creates an easier more consistant interface to deal with in artisan instead of jumping back and forth. In fact abstraction is one of the main principles of composer. We aren't rebuilding on top of it, we just add a layer of abstraction that literally calls `composer x` (though this is likely to change as the next iteration of LPM may run it as a symfony command to handle the edge-cases where composer is not available globally.
4. Package installation should be opt out by default. If a power user is used to running adding things about, then they shouldn't have their app/config/app.php file mucked about with every time they install a new component. There are quite a few packages that I can think of where I do not use the service providers or aliases suggested in favor of the raw API exposed by the objects.
5. There are LPM modules which can be used in other projects (such as Sentry), if the installer was within composer-installer then the package would fail installation outside of Laravel projects which is a huge detriment to interoperability.
6. We are really trying to make as low of a barrier to entry as possible, expecting package developers to create installers or write install script commands is a direct contradiction to this principle.

Don't mean to sound like I'm hounding you, there's a lot to consider in framework development and just wanted to voice a reason for why "this would be a simple fix" isn't the best answer in this case.

**Comment by alexrussell** [comment]
I think you misunderstand installers a little - all a package developer would have to do is specify a `type` of `laravel-package` (or whatever you decide to capture), rather than the default generic `library`, in their `composer.json`, and then in the "extra" section they put what you're wanting them to put in the provides.json:

``` json
{
    "extra": {
        "provides": {
            "service-providers": [
                "My\\Special\\Provider"
            ],
            "aliases": {
                "MyClass": "My\\Special\\Facades\\MyClass"
            },
            "publish-config": true,
            "publish-assets": true,
            "migrate": true
        }
    }
}
```

I'm pretty sure that composer installers don't just run on `composer install` - because you can hook into the `install`, `update` and `uninstall` events - and these aren't events that directly map to composer commands but actual events for individual packages. So if someone removes a line from the "require" array and then run `composer update`, the "uninstall" method should be run of the composer installer.

As for searching, I'd still suggest that people use a tag (`laravel-package` I'd say) so that the packages can be searched on.

I think you're thinking that package developers provide some kind of install script - they don't. It's practically the same as what you have here (just specify a little config and include a specific package type) and the composer installer will do the work required. If I install Sentry and the "laravel composer installer" package is not installed, Sentry gets installed as normal. If the "laravel composer installer" package was present then it'd do the post-install copying and whatnot.

Anyway I understand if you don't like this, that's fair enough. Just means I can start back up on my version of a Laravel package installer :smile:

**Comment by alexrussell** [comment]
Oh and cheers for license clarification, oddly we're talking about Composer but I forgot to look in there!

**Comment by rtablada** [comment]
Got it, it still is a bit of a question of where makes the most sense for the info to be and such. Grabbing the `provides.json` seems to be a nice separation of concerns. Still a bit wary of mucking up the composer.json folder though it is a possibility. I've been taking some hints on other frameworks in things like Ruby and Node. Even though both Gemfile and package.json provide the extra field, it seems a pretty common practice to create your own environment config file (such as Gruntfile, compass.rb, etc).

Like I said before, a lot of the conventions and such will go into discussion as I start working on making this part of core in terms of what makes things best for the framework and PHP in general.

**Comment by alexrussell** [comment]
Yeah - there's nothing wrong with using a separate file, it's just that Composer specifically provides the 'extra' field, and this kind of stuff is what it's for. Again it comes back to the whole reinventing-the-wheel thing I suppose.

I'll keep working on mine anyway and let you know when it's kinda ready to see how you feel about it. It's really small which is great (all the stuff that currently takes four classes with yours is done for me by Composer so I _just_ implement the config rewriting code), but like yours (I think from looking at the code) does kinda rewrite the whole app config file, which will lose things like PHP comments, which is a shame. I guess that can be version 1.1, eh?

It's a shame there doesn't seem to be a way to interact with the running instance of Composer (maybe there is, I haven't looked into it yet) to ask questions like "run this package's migrations?" and "do you mind my automatically adding this to your service providers?", that way point 4 from your list above can be addressed too.

**Comment by rtablada** [comment]
Had to check, but my package does not overwrite the entire file (well technically it does in terms of IO) I only preg_replace the areas within the values of alias and providers (if someone were to dump comments in these arrays they would be lost). :)

I'm starting to talk with Taylor about a Config::persist that would allow this modification to be done within core and abstracted away. But that is in early, early proposal stage.

**Comment by alexrussell** [comment]
Ahh fair enough. Mine just loads the whole config in and then uses `var_export` to spit it back out. But as I said, version 1.1!

I thought yours did the same due to var_export, but it looks like you have a bit of clever code that just `var_export`s the right bit.
